sudo: false
language: java
jdk:
  - oraclejdk8
install: true
before_install:
  - chmod +x gradlew
cache:
  directories:
    - $HOME/.m2
script: ./gradlew clean build
#after_success:
#- bash <(curl -s https://codecov.io/bash)
